- setup_fuse:
  - exec_in: usermod -a -G fuse kameleon
  - append_in:
    - /etc/fuse.conf
    - |
      user_allow_other
- motd_config:
  - write_in:
    - /etc/motd
    - |
      
      ************************** WELCOME TO THE OAR APPLIANCE ************************
      We created 2 fake nodes pointing to localhost (node1 and node2)
      * You can, for example, submit an interactive job:
          $ oarsub -I
      * Or check the API:
          $ wget -O - http://localhost/oarapi/resources.yaml
      * Check the API more deeply, submitting a job as the "$$user_name" user:
          $ curl -i -X POST http://$$user_name:$$user_name@localhost/oarapi-priv/jobs.json \
            -H'Content-Type: application/json' \
            -d '{"resource":"/nodes=1,walltime=00:10:00", "command":"sleep 600"}'
      * Launch the tests: 
          $ cd oar/tests/rspec && make
      * Mount your local git repository for coding:
          $ mkdir git
          $ sshfs -o allow_root your_login@10.0.2.2:git git

      Notes:
        - if you want to change the keyboard mapping, use: 
        'loadkeys <2_letters_country_code>'
        - root password is: $$user_name
      
      ********************************************************************************

