- configure_drawgantt:
  - exec_in: sed -e "s/^\(DB_BASE_LOGIN_RO.*\)oar.*/\1oar_ro/" -i /etc/oar/drawgantt.conf
  - exec_in: sed -e "s/^\(DB_BASE_PASSWD_RO.*\)oar.*/\1oar_ro/" -i /etc/oar/drawgantt.conf

- configure_monika:
  - exec_in: sed -e 's/^\(username\) ?\=.*/\1 = oar_ro/' -i /etc/oar/monika.conf
  - exec_in: sed -e 's/^\(password\) ?\=.*/\1 = oar_ro/' -i /etc/oar/monika.conf

- configure_open_api:
  - exec_in: perl -pi -e "s/Deny from all/#Deny from all/" /etc/oar/apache2/oar-restful-api.conf

- configure_basic_auth_api-priv:
  - write_in:
    - /etc/oar/apache2/oar-restful-api-priv.conf
    - |
      ScriptAlias /oarapi-priv $$oar_prefix_install/lib/cgi-bin/oarapi/oarapi.cgi
      ScriptAlias /oarapi-priv-debug $$oar_prefix_install/lib/cgi-bin/oarapi/oarapi.cgi
      
      <Location /oarapi-priv>
        Options ExecCGI -MultiViews FollowSymLinks
        AuthType      basic
        AuthUserfile  /etc/oar/api-users
        AuthName      "OAR API authentication"
        Require valid-user
        #RequestHeader set X_REMOTE_IDENT %{REMOTE_USER}e
        RewriteEngine On
        RewriteCond %{REMOTE_USER} (.*)
        RewriteRule .* - [E=MY_REMOTE_IDENT:%1]
        RequestHeader add X-REMOTE_IDENT %{MY_REMOTE_IDENT}e
      </Location>
  - exec_in: htpasswd -b -c /etc/oar/api-users kameleon kameleon
  - exec_in: htpasswd -b /etc/oar/api-users oar kameleon

